[package]
name = "nflow-model"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
nflow-core = { path = "../nflow-core" }
candle-core = "0.8"
candle-nn = "0.8"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
